site_name: Poetry Project
repo_url: https://github.com/ArbDigital-art/new_poetry_project
repo_name: arbgigital-art/new_poetry_project

theme:
  name: material
  language: pt-BR
  logo: assets/icon.png
  favicon: assets/icon.png 

markdown_extensions:
  - attr_list

extra_css:
  - css/style.css